name: Infra Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deployment:
    name: Validate & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: Checkout
        uses: actions/checkout@v3
      
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Format
        
        run: terraform fmt
        
      - name: Initialise terraform project
        run: terraform init

      - name: Terraform Plan
        id: Plan
        run: terraform plan -no-color -input=false

      - name: Terraform Apply
        id: Apply
        run: terraform apply -auto-approve -input=false