name: Infra Pipeline

on:
  push:
    branches: [ main ]
  
jobs:
  deployment:
    name: Validate & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: Checkout
        uses: actions/checkout@v3
      
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2

      - name: Format
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform fmt
        
      - name: Initialise terraform project
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init

      - name: Terraform Plan
        id: Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform plan -no-color -input=false

      - name: Terraform Apply
        id: Apply
        run: terraform apply -auto-approve -input=false